-- SoftUni Capstone (Luxe Booking MPA)
-- Initial schema migration.
-- Run this script in the Supabase SQL Editor.
-- NOTE: RLS is intentionally NOT enabled here; it will be configured in 002.

-- 1) profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  created_at timestamptz default now()
);

-- 2) user_roles
create table if not exists public.user_roles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  role text not null check (role in ('admin', 'user')),
  created_at timestamptz default now()
);

-- 3) hotels
create table if not exists public.hotels (
  id bigint generated by default as identity primary key,
  name text not null,
  destination text not null,
  description text,
  created_at timestamptz default now()
);

-- 4) destinations
create table if not exists public.destinations (
  id bigint generated by default as identity primary key,
  name text not null,
  country text not null,
  description text,
  created_at timestamptz default now()
);

-- 5) bookings
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  hotel_id bigint not null references public.hotels(id) on delete restrict,
  start_date date not null,
  end_date date not null,
  guests int not null check (guests > 0),
  note text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  attachment_path text,
  created_at timestamptz default now()
);

-- 6) adventures (simple, read-only MVP)
create table if not exists public.adventures (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  author_name text,
  created_at timestamptz default now()
);

-- Indexes
create index if not exists idx_bookings_user_id on public.bookings(user_id);
create index if not exists idx_bookings_hotel_id on public.bookings(hotel_id);
create index if not exists idx_bookings_status on public.bookings(status);
